from fastapi import status


class StatusCode:
    OK = status.HTTP_200_OK
    CREATED = status.HTTP_201_CREATED
    ACCEPTED = status.HTTP_202_ACCEPTED
    NO_CONTENT = status.HTTP_204_NO_CONTENT

    BAD_REQUEST = status.HTTP_400_BAD_REQUEST
    UNAUTHORIZED = status.HTTP_401_UNAUTHORIZED
    FORBIDDEN = status.HTTP_403_FORBIDDEN
    NOT_FOUND = status.HTTP_404_NOT_FOUND
    CONFLICT = status.HTTP_409_CONFLICT
    UNPROCESSABLE_CONTENT = status.HTTP_422_UNPROCESSABLE_CONTENT
    TOO_MANY_REQUESTS = status.HTTP_429_TOO_MANY_REQUESTS

    INTERNAL_SERVER_ERROR = status.HTTP_500_INTERNAL_SERVER_ERROR
